<template>
	<div class="container lineTop">
		<div>
			
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="color:#333333; font-family:宋体; font-size:12pt; font-weight:bold">&nbsp;</span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; text-indent:15pt; widows:0"><span style="font-family:宋体; font-size:12pt">本《用户协议》（以下称“本协议”）是由您（以下称“用户”</span><span style="font-family:宋体; font-size:12pt">或</span><span style="font-family:宋体; font-size:12pt">“您”</span><span style="font-family:宋体; font-size:12pt">）与</span><span style="font-family:宋体; font-size:12pt">天天逛街信息科技发展有限公司</span><span style="font-family:宋体; font-size:12pt">（以下称“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”）就用户使用“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”提供的</span><span style="font-family:宋体; font-size:12pt">相关</span><span style="font-family:宋体; font-size:12pt">互联网</span><span style="font-family:宋体; font-size:12pt">信息</span><span style="font-family:宋体; font-size:12pt">服务（包括但不限于：</span><span style="font-family:宋体; font-size:12pt">天天逛街微信小程序</span><span style="font-family:宋体; font-size:12pt">、</span><span style="font-family:宋体; font-size:12pt">天天逛街APP</span><span style="font-family:宋体; font-size:12pt">等）所订立的相关权利义务规范。本服务条款对用户和“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”均具有法律效力。本协议连同所有更新材料、补充条款以及“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”的其他规则和政策共同构成了用户与“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”之间的协议。</span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; text-indent:15pt; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; text-indent:15pt; widows:0"><span style="font-family:宋体; font-size:12pt">在使用</span><span style="font-family:宋体; font-size:12pt">“天天逛街”</span><span style="font-family:宋体; font-size:12pt">服务前，请您务必仔细阅读并透彻理解本</span><span style="font-family:宋体; font-size:12pt">协议</span><span style="font-family:宋体; font-size:12pt">，在确认充分理解并同意后使用相关产品或服务。一旦您通过任何方式使用“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”服务，或者获得“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”软件提供的任何服务 ，则代表您充分理解并同意本</span><span style="font-family:宋体; font-size:12pt">协议</span><span style="font-family:宋体; font-size:12pt">，完全接受本协议的全部内容，并自愿受本协议的约束</span><span style="font-family:宋体; font-size:12pt">。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;&nbsp; </span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; text-indent:15pt; widows:0"><span style="font-family:宋体; font-size:12pt; text-decoration:underline">阅读本协议过程中，如果您不同意本协议或其中任何条款，请立即停止注册程序并停止使</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">用“</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">天天逛街</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">”</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">平台服务。</span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; text-indent:-24pt; widows:0"><span style="font-family:宋体; font-size:12pt; font-weight:bold">一、</span><span style="font-family:宋体; font-size:12pt; font-weight:bold">账号注册与使用</span><br><span style="font-family:宋体; font-size:12pt; font-weight:bold">&nbsp;</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="color:#333333; font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="color:#333333; font-family:宋体; font-size:12pt">用户在使用“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#333333; font-family:宋体; font-size:12pt">”服务时可能需要注册一个账号，账号注册成功后，将产生“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#333333; font-family:宋体; font-size:12pt">”账号及相应的用户名和密码等账号信息。“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#333333; font-family:宋体; font-size:12pt">”账号的所有权归“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#333333; font-family:宋体; font-size:12pt">”所有，用户完成申请注册手续后，获得“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#333333; font-family:宋体; font-size:12pt">”账号的使用权，该使用权仅属于初始申请注册人，禁止赠与、借用、租用、转让或售卖，用户应谨慎合理地保存、使用其用户名和密码。</span><br><span style="color:#333333; font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="color:#333333; font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="color:#000000; font-family:宋体; font-size:12pt">用户在注册及使用“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”服务时，必须向“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”提供真实、准确、完整、合法有效的资料，且有义务维持并及时更新相关资料。用户应当保证在账号名称、头像和简介等注册信息中不得出现违法和不良信息。如果用户提供的资料违反本款要求，用户需承担因此引起的相应责任及后果，并且“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”保留终止用户使用“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”各项服务或采取其他处理措施的权利。</span><br><span style="color:#333333; font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="color:#333333; font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="color:#000000; font-family:宋体; font-size:12pt">作为“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”服务的提供者，为使用户更好地使用“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”的各项服务，保障用户的账号安全，“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”有权要求用户按照我国法律规定完成实名认证。</span><br><span style="color:#333333; font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="color:#333333; font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="color:#000000; font-family:宋体; font-size:12pt; text-decoration:underline">用户应当对以其用户账号进行的所有活动和事件负法律责任。</span><span style="color:#000000; font-family:宋体; font-size:12pt">用户同意在任何情况下不使用其他用户的账号或密码，不得冒充他人，也不得恶意使用注册账号导致其他用户误认，否则“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”有权立即停止提供服务，收回其账号并由用户独自承担由此而产生的一切法律责任。在用户怀疑他人使用其账号或密码时，用户同意立即通知“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”并按照“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”的要求提供相关身份证明文件等材料，同意授权“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”采取一切合理措施</span><span style="color:#000000; font-family:宋体; font-size:12pt">以保证用户的利益不受损害，并认可该等措施所产生的法律效果归于用户自身。</span><span style="color:#000000; font-family:宋体; font-size:12pt; text-decoration:underline">因黑客行为或用户的保管疏忽等非“</span><span style="color:#333333; font-family:宋体; font-size:12pt; text-decoration:underline">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt; text-decoration:underline">”的原因导致账号、密码遭他人非法使用，“</span><span style="color:#333333; font-family:宋体; font-size:12pt; text-decoration:underline">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt; text-decoration:underline">”不承担任何责任。</span><br><span style="color:#333333; font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="color:#333333; font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="color:#000000; font-family:宋体; font-size:12pt">您了解并同意，一经注册用户账号，即视为您同意</span><span style="color:#000000; font-family:宋体; font-size:12pt">“</span><span style="color:#000000; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”</span><span style="color:#000000; font-family:宋体; font-size:12pt">及/或其关联公司通过短信或者电子邮件的方式向您注册时填写的手机号码或者电子邮箱发送相应的产品服务广告信息、促销优惠等营销信息；您如果不同意发送，您可以通过相应的退订功能进行退订</span><br><span style="color:#333333; font-family:宋体; font-size:12pt">&nbsp;</span></li>
			</ol>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="color:#333333; font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; text-indent:-24pt; widows:0"><span style="font-family:宋体; font-size:12pt; font-weight:bold">二、</span><span style="font-family:宋体; font-size:12pt; font-weight:bold">平台服务与用户使用规范</span><br><span style="font-family:宋体; font-size:12pt; font-weight:bold">&nbsp;</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”提供服务的具体内容由“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”根据实际情况决定，“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”保留随时变更、中断或终止部分或全部服务的权利，“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”不承担因业务调整给用户造成的损失。除非本协议另有其他明示规定，调整、增加或者强化“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”服务中的任何功能，均受到本协议之规范。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”是一个信息分享、传播及获取的平台，用户通过“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">获取、</span><span style="font-family:宋体; font-size:12pt">发表的信息为公开的信息，其他第三方均可以通过“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”进行获取，用户对任何信息的发表即认可该信息为公开的信息，任何用户不愿被其他第三方获知的信息都不应该在“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”上进行发表。如根据相关法律法规的规定，其他第三方获取用户发表的信息需要另行取得用户同意的，由该第三方与用户自行协商解决，第三方的行为与“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”无关，同时用户与第三方的任何合作均不应违反本协议约定。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">用户承诺不得以任何方式利用“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”直接或间接从事违反中国法律以及社会公德的行为，“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”有权对违反上述承诺的内容予以删除。用户在使用“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”服务时所传送、发布的任何内容仅表明其个人的观点和立场，并不反映或代表，也不得被视为反映或代表“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”的观点、立场或政策；用户作为内容的发布者，需自行对所发布内容负责并承担全部法律责任。</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">“</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">天天逛街</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">”不对用户传送、发布的内容的正确性、完整性进行保证，除法律法规规定的义务外，“</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">天天逛街</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">”不承担任何其他责任。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">您应当遵守国家有关法律法规，不得在</span><span style="font-family:宋体; font-size:12pt">“天天逛街”</span><span style="font-family:宋体; font-size:12pt">平台当中发表、转发或者传播含有下列内容的信息:</span><br><br><span style="font-family:宋体; font-size:12pt">1）</span><span style="font-family:宋体; font-size:12pt">反对宪法所确定的基本原则的;</span><br><span style="font-family:宋体; font-size:12pt">2）</span><span style="font-family:宋体; font-size:12pt">危害国家安全、泄露国家秘密、颠覆国家政权、破坏国家统</span><span style="font-family:宋体; font-size:12pt">一的</span><span style="font-family:宋体; font-size:12pt">;</span><br><span style="font-family:宋体; font-size:12pt">3）</span><span style="font-family:宋体; font-size:12pt">损害国家荣誉和利益的;</span><br><span style="font-family:宋体; font-size:12pt">4）</span><span style="font-family:宋体; font-size:12pt">煽动民族仇恨、民族歧视，破坏民族团结的;</span><br><span style="font-family:宋体; font-size:12pt">5）</span><span style="font-family:宋体; font-size:12pt">破坏国家宗教政策，宣扬邪教和封建迷信的;</span><br><span style="font-family:宋体; font-size:12pt">6）</span><span style="font-family:宋体; font-size:12pt">散布谣言，扰乱社会秩序，破坏社会稳定的;</span><br><span style="font-family:宋体; font-size:12pt">7）</span><span style="font-family:宋体; font-size:12pt">散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的;</span></li>
			</ol>
			<p style="margin:0pt 0pt 0pt 0pt; orphans:0; text-align:left; widows:0"><span style="font-family:宋体; font-size:12pt">8）</span><span style="font-family:宋体; font-size:12pt">侮辱或者诽谤他人，侵害他人合法权益的;</span></p>
			<p style="margin:0pt 0pt 0pt 0pt; orphans:0; text-align:left; widows:0"><span style="font-family:宋体; font-size:12pt">9）</span><span style="font-family:宋体; font-size:12pt">含有法律、行政法规禁止的其他内容的。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<ol start="5" type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">“天天逛街”</span><span style="font-family:宋体; font-size:12pt">从不鼓励进行任何造成数据异常的行为，包含赞、关注、取消关注、评论等互动方式，同时因为用户个人原因造成的账号安全风险和财产风险</span><span style="font-family:宋体; font-size:12pt">“天天逛街”</span><span style="font-family:宋体; font-size:12pt">概不担责，并保留追加惩罚的权利；</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="background-color:#ffffff; color:#333333; font-family:宋体; font-size:12pt; line-height:13.5pt; margin:0pt 0pt 0pt 17pt; padding-left:1pt; text-indent:0pt"><span style="color:#333333; font-family:宋体; font-size:12pt; text-decoration:underline">您了解并同意</span><span style="color:#333333; font-family:宋体; font-size:12pt; text-decoration:underline">：</span><br><br><span style="color:#333333; font-family:宋体; font-size:12pt">1)</span><span style="color:#333333; font-family:宋体; font-size:12pt; text-decoration:underline">您违反上述承诺时，</span><span style="color:#333333; font-family:宋体; font-size:12pt; text-decoration:underline">“天天逛街”</span><span style="color:#333333; font-family:宋体; font-size:12pt; text-decoration:underline">有权依据本服务条款的约定，做出相应处理或终止向您提供服务，且无须征得您的同意或提前通知于您。</span><br><br><span style="color:#333333; font-family:宋体; font-size:12pt">2)</span><span style="color:#333333; font-family:宋体; font-size:12pt">“天天逛街”</span><span style="color:#333333; font-family:宋体; font-size:12pt">有权采取相应措施，包括但不限于直接屏蔽、删除侵权信息、降低您的信用值或直接停止提供服务。</span><br><br><span style="color:#333333; font-family:宋体; font-size:12pt">3</span><span style="color:#333333; font-family:宋体; font-size:12pt">)</span><span style="color:#333333; font-family:宋体; font-size:12pt">对于您涉嫌违反承诺的行为产生的一切法律后果，包含但不限于对任意第三方造成损害的，您均应当以自己的名义独立承担所有的法律责任，并应确保</span><span style="color:#333333; font-family:宋体; font-size:12pt">“天天逛街”</span><span style="color:#333333; font-family:宋体; font-size:12pt">免于承担因此产生的损失或增加的费用。</span><br><br><span style="color:#000000; font-family:宋体; font-size:12pt">4</span><span style="color:#000000; font-family:宋体; font-size:12pt">)</span><span style="color:#000000; font-family:宋体; font-size:12pt">如您涉嫌违反有关法律或者本服务条款之规定，使</span><span style="color:#333333; font-family:宋体; font-size:12pt">“天天逛街”</span><span style="color:#000000; font-family:宋体; font-size:12pt">遭受任何损失，或受到任何第三方的索赔，或受到任何行政管理部门的处罚，您应当赔偿</span><span style="color:#333333; font-family:宋体; font-size:12pt">“天天逛街”</span><span style="color:#000000; font-family:宋体; font-size:12pt">因此造成的损失及（或）发生的费用，包括合理的律师费用。</span><br><span style="color:#333333; font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="background-color:#ffffff; color:#333333; font-family:宋体; font-size:12pt; line-height:13.5pt; margin:0pt 0pt 0pt 17pt; padding-left:1pt; text-indent:0pt"><span style="color:#000000; font-family:宋体; font-size:12pt">其他“</span><span style="color:#000000; font-family:宋体; font-size:12pt">天天逛街</span><span style="color:#000000; font-family:宋体; font-size:12pt">”不时发布、修改或完善的相关规则。</span><br><span style="color:#000000; font-family:宋体; font-size:12pt">以上各项规则为本协议的重要组成部分，如各项具体规则的内容与本协议存在冲突，或者本协议未进行明确规定的，均应以各项规则的内容为准。</span></li>
			</ol>
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt; font-weight:bold">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; text-indent:-24pt; widows:0"><span style="font-family:宋体; font-size:12pt; font-weight:bold">三、</span><span style="font-family:宋体; font-size:12pt; font-weight:bold">知识产权</span><span style="font-family:宋体; font-size:12pt; font-weight:bold">保护</span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">用户在“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”上发表的内容</span><span style="font-family:宋体; font-size:12pt">，</span><span style="font-family:宋体; font-size:12pt">知识产权均归用户本人或其他合法知识产权人所有。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">用户承诺，其发布在“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”上的全部内容（包括但不限于：文字、图片或影音资料等）系用户原创或已经取得相关权利人的事先书面许可，不存在任何权利瑕疵或负担。如果第三方提出关于知识产权的异议，“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”有权根据相关法律法规的要求并结合实际情况对相关内容采取删除、屏蔽、断开链接等处理措施，且有权追究用户的法律责任；如因此给“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">或任何第三方造成损失的，用户应负责赔偿</span><span style="font-family:宋体; font-size:12pt">。 </span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">对于您在任何时间以任何形式向</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">提供或在</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台发表的信息或资料(包括但不限于文字、图片、视频、音频等)相关知识产权，您同意免费授予</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">及其关联公司获得全球排他的许可使用权利及再授权给其他第三方使用的权利。您同意</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">及其关联公司存储、</span><span style="font-family:宋体; font-size:12pt">使用、复制、修订、编辑、发布、展示、翻译、分发您的非个人信息或制作其派生作品，并以已知或日后开发的形式、媒体或技术将.上述信息纳入其他作品内。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">我们尊重知识产权，反对并打击侵犯知识产权的行为。知识产权权利人若认为</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">内容侵犯其合法权益的，可以通过</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">客服</span><span style="font-family:宋体; font-size:12pt">进行</span><span style="font-family:宋体; font-size:12pt">相关</span><span style="font-family:宋体; font-size:12pt">投诉，我们将在收到知识产权权利人合格通知后依据相应的法律法规以及平台规则及时处理。</span><span style="font-family:宋体; font-size:12pt">同时</span><span style="font-family:宋体; font-size:12pt">，</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">“</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">天天逛街</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">”作为网络服务提供者，对非法转载、虚假发布、盗版行为的发生不具备充分的监控能力；“</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">天天逛街</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">”对他人在网站上实施的此类侵权行为不承担法律责任，侵权责任概由实施方承担</span><span style="color:#333333; font-family:宋体; font-size:12pt; text-decoration:underline">。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”提供的服务中使用的商业标识、版面设计、排版方式、文字、图片、图形、音频、视频、有关数据等内容及资源的著作权、商标权、专利权、商业秘密等知识产权均归“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”或“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”指定的第三方所有，均受法律法规和相应的国际条约的保护，但相关权利人依照法律规定应享有的权利除外。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
			</ol>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; text-indent:-24pt; widows:0"><span style="font-family:宋体; font-size:12pt; font-weight:bold">四、</span><span style="font-family:宋体; font-size:12pt; font-weight:bold">商品交易</span><br><span style="font-family:宋体; font-size:12pt; font-weight:bold">&nbsp;</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">当您在</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台购买商品或服务时，请您务必仔细确认所购商品的名称、价格、数量、型号、规格、尺寸或服务的时间、内容、限制性要求等重要事项，并在下单时核实您的联系地址、电话、收货人等信息。如您填写的收货人非您本人，则该收货人的行为和意思表示产生的法律后果均由您承担。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">您的购买行为应当基于真实的消费需求，不得实施恶意购买、恶意维权等扰乱</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台正常交易秩序的行为。基于维护</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台交易秩序及交易安全的需要，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">发现上述情形时有权采取关闭相关交易订单，限制账户使用功能、中止或终止服务等措施而无需事先通知您。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt; text-decoration:underline">您通过</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">“</span><span style="color:#333333; font-family:宋体; font-size:12pt; text-decoration:underline">天天逛街</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">”</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">平台下达订单后，仅表示系统接收到了您下达的订单，只有销售方将订单中的商品实际向您发出时(以销售方点击发货的时间为准)，您与销售方之间的买卖合同才成立。</span><span style="font-family:宋体; font-size:12pt">此外，如果您在一份订单里订购了多种商品并且销售方只给您发出了部分商品时，您与销售方之间仅就销售方已经发出的那一部分商品成立买卖合同。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">您有权在</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台提供的评价系统中对您购买的商品或服务进行评价。您的所有评价行为应遵守</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">规则的相关规定，评价内容应当客观真实，不应包含任何污言秽语、色情低俗、广告信息及法律法规与本协议列明的其他禁止性信息;您不得以不正当方式帮助他人提升信用或利用评价权利对其他用户实施威胁、敲诈勒索。</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">可按照法律法规及/或</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">规则的相关规定对您发布的违规评价信息进行删除或屏蔽。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">除另有明确说明外，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台，上销售的商品/服务的相关信息由商家自行制作、上传， </span><span style="font-family:宋体; font-size:12pt">“天天逛街”</span><span style="font-family:宋体; font-size:12pt">尽可能通过与商家签订合作协议及发布平台规则等方式约束商</span><span style="font-family:宋体; font-size:12pt">家提供准确、完整、可靠、有效、没有错误和误导性的商品描述。然而，</span><span style="font-family:宋体; font-size:12pt">您充分理解，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台上存在海量信息，因为互联网技术及人力的局限性，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">不能保证平台上所有商品的信息均准确、完整、可靠、有效、没有错误和没有误导性。除</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">有明显过错外，对于因商品信息导致的纠纷，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">不承担任何责任。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">发现您通过</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台下达的订单存在违反法律规定或者本协议约定的异常情形的，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">有权采取关闭相关交易订单、限制账户使用功能、中止或终止服务等措施而无需事先通知您</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">如果您使用</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台时存在违反国家法律法规、本协议、侵害他人利益、</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">利益或社会公共利益、严重违背社会公德等情形，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">有权采取删除相关信息、中止或终止提供服务等处理措施。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">您理解并同意，因您违反本协议或</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">规则而产生的第三方索赔请求，由您自行承担法律责任;由此导致</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">遭受损失的，您也应当一并赔偿。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">费用</span><br><span style="font-family:宋体; font-size:12pt">除本协议另有约定外，</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">“</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">天天逛街</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">”</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">平台暂时为您提供免费服务</span><span style="font-family:宋体; font-size:12pt">，不向您收取任何费用。但</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">保留收费的权利，包括设置收费的软件功能，决定收费对象、收费时段或收费费率等。</span></li>
			</ol>
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; text-indent:-24pt; widows:0"><span style="font-family:宋体; font-size:12pt; font-weight:bold">五、</span><span style="font-family:宋体; font-size:12pt; font-weight:bold">免责声明</span><br><span style="font-family:宋体; font-size:12pt; font-weight:bold">&nbsp;</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:4pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">将根据</span><span style="font-family:宋体; font-size:12pt">相关</span><span style="font-family:宋体; font-size:12pt">法律法规</span><span style="font-family:宋体; font-size:12pt">要求对</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">网站上的商品、服务、广告等信息进行合理审核，但无法保证</span><span style="font-family:宋体; font-size:12pt">其</span><span style="font-family:宋体; font-size:12pt">准确性和完整性</span><span style="font-family:宋体; font-size:12pt">。</span><span style="font-family:宋体; font-size:12pt">同时，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">服务的内容可能涉及由第三方个人或单位提供，第三方所提供的服务品质及内容由第三方自行负责；第三方的内容、商品、服务、广告和其他任何信息均需由用户自行判断并承担风险，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">不保证其内容及网络服务的及时性、安全性、准确性，若因此引发任何争议或损害，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">对此不承担责任。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:4pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">不保证服务一定能满足用户的要求，对于因不可抗力或</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">不能控制的原因造成的服务中断或其它缺陷，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">不承担任何责任，但将合理审慎地采取必要措施减少因此而给用户造成的损失和影响。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:4pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">用户理解，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">需要定期或不定期地对提供网络服务的平台（如互联网网站、移动网络等）或相关的设备进行检修、维护或升级，如因此类情况造成网络服务在合理时间内的中断，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">无需为此承担任何责任，但</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">将尽可能事先进行通告。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:4pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">用户理解并确认，在使用本服务过程中存在来自任何他人的包括误导性的、欺骗性的、威胁性的、诽谤性的、令人反感的或非法的信息，或侵犯他人权利的匿名或冒名的信息，以及伴随该等信息的行为，对此还请用户谨慎判断，不要轻信该等信息以致产生损失，因此导致用户或第三方的任何损失的，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">将会向用户提供必要的帮助，但不承担任何责任。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:4pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">在任何情况下，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">均不对任何间接性、后果性、惩罚性、偶然性、特殊性或刑罚性的损害承担责任，包括因用户使用</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">服务而遭受的利润损失等，即使</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">已被告知该等损失的可能性亦然。</span></li>
			</ol>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; text-indent:-24pt; widows:0"><span style="font-family:宋体; font-size:12pt; font-weight:bold">六、</span><span style="font-family:宋体; font-size:12pt; font-weight:bold">用户隐私制度</span><br><span style="font-family:宋体; font-size:12pt; font-weight:bold">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; text-indent:-18pt; widows:0"><span style="font-family:宋体; font-size:12pt">1、</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”将</span><span style="font-family:宋体; font-size:12pt">在</span><span style="font-family:宋体; font-size:12pt">“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">网站</span><span style="font-family:宋体; font-size:12pt">公布并不时修订</span><span style="font-family:宋体; font-size:12pt">《</span><span style="font-family:宋体; font-size:12pt">隐私政策</span><span style="font-family:宋体; font-size:12pt">》</span><span style="font-family:宋体; font-size:12pt">，</span><span style="font-family:宋体; font-size:12pt">隐私</span><span style="font-family:宋体; font-size:12pt">政策</span><span style="font-family:宋体; font-size:12pt">构成本协议的有效组成部分。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; text-indent:-18pt; widows:0"><span style="font-family:宋体; font-size:12pt">2、</span><span style="font-family:宋体; font-size:12pt">您知悉并承诺在使用“</span><span style="color:#333333; font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”的服务过程中，遵守《</span><span style="font-family:宋体; font-size:12pt">隐私政策</span><span style="font-family:宋体; font-size:12pt">》</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt; text-decoration:underline">具体条款内容，请登陆“天天逛街”</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">网站</span><span style="font-family:宋体; font-size:12pt; text-decoration:underline">查阅</span></p>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; text-indent:-24pt; widows:0"><span style="font-family:宋体; font-size:12pt; font-weight:bold">七、</span><span style="font-family:宋体; font-size:12pt; font-weight:bold">协议变更与终止</span><br><span style="font-family:宋体; font-size:12pt; font-weight:bold">&nbsp;</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">根据互联网的发展和有关法律、法规及规范性文件的变化，或者因业务发展需要，“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”将在必要时对本协议的服务条款作出修改或变更。“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”将会直接在“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”网站及App上公布修改之后的协议内容，该公布行为视为“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”已经通知用户修改内容，修改后的内容一经公布即有效替代原有服务条款。“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”也可采用电子邮件或私信的传送方式，提示用户协议条款的修改、服务变更、或其它重要事项。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">此外，用户可登录“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”网站或在“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">微信小程序、</span><span style="font-family:宋体; font-size:12pt">App</span><span style="font-family:宋体; font-size:12pt">客户</span><span style="font-family:宋体; font-size:12pt">端中查阅最新版本的相关协议条款。如果用户继续使用“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”提供的服务，即视为用户已经接受修改后的服务条款；如果用户不接受修改后的服务条款，应当停止使用“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”提供的服务。</span></li>
			</ol>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<ol start="3" type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">基于平台服务的安全性，有权中止向您提供部分或全部</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台服务，暂时冻结您的账户，待安全问题解决后及时恢复，并对中止、冻结及恢复的事实及时通知。如果网站的安全问题是由于您的违法行为引起，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">有权终止向您提供部分或全部</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台服务，永久冻结（注销）您的帐户，并有权向您对损失进行索赔。</span></li>
			</ol>
			<p style="margin:0pt; orphans:0; text-align:justify; text-indent:24pt; widows:0"><span style="font-family:Calibri; font-size:12pt">&nbsp;</span></p>
			<ol start="4" type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">如您对本协议的修改有异议，或对</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">的服务不满，可以行使如下权利：</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
			</ol>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="font-family:Calibri; font-size:12pt">1</span><span style="font-family:宋体; font-size:12pt">）</span><span style="font-family:宋体; font-size:12pt">停止使用</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">所提供的</span><span style="font-family:宋体; font-size:12pt">服务；</span><br><span style="font-family:Calibri; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="font-family:Calibri; font-size:12pt">2</span><span style="font-family:宋体; font-size:12pt">）</span><span style="font-family:宋体; font-size:12pt">通过客服渠道告知</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">停止对其服务。结束服务后，您使用</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">服务的权利立即终止。在此情况下，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">没有义务传送任何未处理的信息或未完成的服务给您或任何无直接关系的第三方。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<ol start="5" type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">您同意与</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">的协议关系终止后，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">仍享有下列权利：</span><br><br><span style="font-family:Calibri; font-size:12pt">1) </span><span style="font-family:宋体; font-size:12pt">继续保存您未及时删除的注册信息及您使用</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台服务期间发布的所有信息至法律规定的记录保存期满。</span><br><br><span style="font-family:Calibri; font-size:12pt">2</span><span style="font-family:宋体; font-size:12pt">）您在使用</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">平台服务期间存在违法行为或违反本协议和</span><span style="font-family:Calibri; font-size:12pt">/</span><span style="font-family:宋体; font-size:12pt">或规则的行为的，</span><span style="font-family:宋体; font-size:12pt">“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”</span><span style="font-family:宋体; font-size:12pt">仍可依据本协议向您主张权利、追究责任。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">由于</span><span style="font-family:宋体; font-size:12pt">国家政策变化或</span><span style="font-family:宋体; font-size:12pt">不可抗力</span><span style="font-family:宋体; font-size:12pt">所造成</span><span style="font-family:宋体; font-size:12pt">的问题，导致</span><span style="font-family:宋体; font-size:12pt">双方无法履行义务；</span></li>
			</ol>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 18pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
			<p style="margin:0pt 0pt 0pt 24pt; orphans:0; text-align:justify; text-indent:-24pt; widows:0"><span style="font-family:宋体; font-size:12pt; font-weight:bold">八、</span><span style="font-family:宋体; font-size:12pt; font-weight:bold">争议解决</span><br><span style="font-family:宋体; font-size:12pt; font-weight:bold">&nbsp;</span></p>
			<ol type="1" style="margin:0pt; padding-left:0pt">
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">本协议之订立、生效、解释、修订、补充、终止、执行与争议解决均适用中华人民共和国法律，如法律无相关规定的，则应参照通用国际商业惯例和（或）行业惯例。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">本协议任一条款被视为废止、无效或不可执行，该条应视为可分的且并不影响本协议其余条款的有效性及可执行性。</span><br><span style="font-family:宋体; font-size:12pt">&nbsp;</span></li>
				<li style="font-family:宋体; font-size:12pt; margin:0pt 0pt 0pt 17pt; orphans:0; padding-left:1pt; text-align:justify; text-indent:0pt; widows:0"><span style="font-family:宋体; font-size:12pt">因本协议产生之争议</span><span style="font-family:宋体; font-size:12pt">或</span><span style="font-family:宋体; font-size:12pt">纠纷，</span><span style="color:#333333; font-family:宋体; font-size:12pt">首先应友好协商解决，</span><span style="font-family:宋体; font-size:12pt">协商不成的，</span><span style="font-family:宋体; font-size:12pt">用</span><span style="font-family:宋体; font-size:12pt">户同意将纠纷或争议提交“</span><span style="font-family:宋体; font-size:12pt">天天逛街</span><span style="font-family:宋体; font-size:12pt">”所在地有管辖权的人民法院管辖。</span></li>
			</ol>
			<p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:宋体; font-size:12pt">&nbsp;</span></p>
		</div>
	</div>
</template>
<script>
	export default {
		data() {
			return {

			};
		},
		components: {},
		computed() {},
		methods: {
			//退出
			async quitLogin() {

				this.$router.push({
					path: '/pages/home/home',
					isTab: true
				})
			}
		},
		computed: {

		},
		mounted() {},
		onPullDownRefresh() {},
		async onShow() {}
	};
</script>
<style scoped lang='scss'>
	.container {
		padding: 0 15px;
		span {
			font-size: 12px !important;
			word-spacing:14px !important;
			line-height: 18px !important;
			padding-bottom:2px !important;
		}
		ol,
		li,
		span {
			margin-left: 0 !important;
			font-family:PingFang-SC-Regular !important;
			font-size: 12px !important;
			word-spacing:14px !important;
			line-height: 18px;
			padding-bottom:2px;
		}
		p{
			font-family:PingFang-SC-Regular !important;
			font-size: 12px !important;
			word-spacing:14px !important;
		line-height: 18px !important;
		padding-bottom:2px !important;
		}
	}
</style>